### PR TITLE
Make initialization checks thread safe

### PR DESCRIPTION
**Pull request by clarksandholtz**
**Description**

Added a safety check to not attempt initialization twice. Also made sure the `assertInitialization` check will never have a race condition with the `initialize` function as they both need to access a lock on the `Catch` object.

**Open Questions**

**Testing**

**Relevant Links (e.g. Ticket)**

**TODOs**

### CODE REVIEW

**Comment by clarksandholtz** [comment]
Current dependencies on/for this PR:
* main
  * **PR #160** <a href="https://app.graphite.dev/github/pr/getcatch/catch-android-sdk/160" target="_blank">Graphite</a> 
    * **PR #162** <a href="https://app.graphite.dev/github/pr/getcatch/catch-android-sdk/162" target="_blank">Graphite</a> 
      * **PR #163** <a href="https://app.graphite.dev/github/pr/getcatch/catch-android-sdk/163" target="_blank">Graphite</a> 
        * **PR #164** <a href="https://app.graphite.dev/github/pr/getcatch/catch-android-sdk/164" target="_blank">Graphite</a>  👈
          * **PR #161** <a href="https://app.graphite.dev/github/pr/getcatch/catch-android-sdk/161" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-android-sdk/164?utm_source=stack-comment).

**Review by lucillebenoit — APPROVED** [review]
🚀

**Comment by clarksandholtz** [comment]
@clarksandholtz started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-android-sdk/164).

**Comment by clarksandholtz** [comment]
[Graphite](https://app.graphite.dev/github/pr/getcatch/catch-android-sdk/164) rebased this pull request as part of a merge.

**Comment by clarksandholtz** [comment]
@clarksandholtz merged this pull request with [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-android-sdk/164).

**Pull request merged**
